### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tracer')

### ISSUE THREAD

**Issue by kenvogg** [zemse/hardhat-tracer#11]
When I tried:

     import { hre } from 'hardhat';
    
     // ... deploy fooContract ...
     hre.tracer.nameTags[fooContract.address] = "fooContract";

I was met with a bunch of `TypeError: Cannot read properties of undefined (reading 'tracer')` 

How could we fix this? I'm assuming just some incompatibilities with TypeScript

**Comment by zemse** [comment]
Can you confirm if `import 'hardhat-tracer'` present in your hardhat config?

**Comment by kenvogg** [comment]
@zemse Yes, and if I don't attempt to set nameTags, hardhat-tracer works as expected.

**Comment by kenvogg** [comment]
Any more thoughts? If you need more info about my setup, I can share. I think it is a pretty standard hardhat project though.

**Comment by zemse** [comment]
I think this was because of old versions in hardhat-tracer (since the plugin wasn't updated since long time).

Just rewrote the plugin and released [v1.1.0-rc.1](https://github.com/zemse/hardhat-tracer/releases/tag/v1.1.0-rc.1). If you can, please try and let me know if there are any issues with this.

**Comment by kenvogg** [comment]
Yep works fine now 🥳
