### ISSUE TITLE
Add support for gas consumption logging

### ISSUE THREAD

**Issue by Rubilmax** [zemse/hardhat-tracer#35]
It would be handy to be able to follow the gas consumption of each trace, just like foundry is doing:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/3147812/224744642-cdfb4600-079e-4084-bd69-4e62a48c487e.png">

In this case, foundry is logging the remaining gas of each context at the start of each line

**Comment by Rubilmax** [comment]
Wonderful! I think it's ok to keep it disabled by default, because it's unnecessarily overwhelming if you don't use it (anyway, choose what you prefer!)

But seeing it made me think that adding contrast to the traces would have much benefit to ease reading them!
For example, making the gas consumption gray by default would make them less overwhelming:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/3147812/224771036-599b7d93-65e4-4165-9823-9b564a677127.png">

Or even better: provide a way to customize the colors?

Anyway, this plugin is already great and very useful as it is!

**Comment by zemse** [comment]
Yeah I should update the docs for this. And seems the color for the `gasLimit` and `gasUsed` is missing, adding this to the list of my todos. 

The customization of colors through the hardhat config might need some refactoring work since they are hardcoded [here](https://github.com/zemse/hardhat-tracer/blob/main/src/utils/colors.ts). Just like naming variables, I think choosing colors is a difficult job for me lol, so I initially took inspiration from Javascript/Solidity code. If you have ideas about better coloring schemes or layout of the trace, please do let me know. Having more information available in a readable/less overwhelming manner would definitely be great.

**Comment by Rubilmax** [comment]
I'd be glad to dive into this and propose a PR to update the colors!
