### ISSUE TITLE
It's too slow when tracing tx, and takes a long time when the data is large

### ISSUE THREAD

**Issue by hexiaoyanh** [zemse/hardhat-tracer#41]
npx hardhat trace --hash 0x48e52a12cb297354a2a1c54cbc897cf3772328e7e71f51c9889bb8c5e533a934 --network bsc

**Comment by zemse** [comment]
If you are using an archive node that does not support tracing then in order to generate a trace, it has to load a lot of state data from the archive node and yeah that can be a lot of time for a transaction that touches a lot of accounts. If your remote node supports standard trace RPCs like `debug_traceTransaction` it should be faster.

You may just try online services like http://tenderly.co for seeing traces on live network transactions, it's very helpful for debugging. The trace task of this plugin definately takes more time than online services since it does not have the archive data, so use case is very limited. I only use it when I want to change bytecode of a contract in the trace (typically for seeing trace along with console logs).
